### ISSUE TITLE
Edit Cohort Type – Description is not appearing at the time of edit

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#19]
Edit Cohort Type – Description is not appearing at the time of edit.(The same bug should be fixed in all the other modules)

**Comment by bholagabbar** [comment]
I think an old version of the module has deployed on your system. This _was_ an issue but has been resolved in the current code. I have attached a screenshot of this working on my system. <br>
The problem was the in the old code, we had something like `<textarea value="${status.value}> </>` but  `textarea` has no `value` attribute. This was changed to `<textarea>${status.value} </>` in the current code. 

![capture](https://cloud.githubusercontent.com/assets/11693595/17331249/bf1e4820-58e7-11e6-8b41-492446d3c86e.PNG)

**Comment by zohaibihs** [comment]
Yes , I have verified it on the latest build and  bug is resolved .
