### ISSUE TITLE
Edit of records is not working fine as record is not getting edited for all metadata

### ISSUE THREAD

**Issue by zohaibihs** [OpenSRP/openmrs-module-cohort#20]
10- Edit Cohort Type – Edit of record is not working fine as record is not getting edited 
(The same bug should be fixed in all the other modules).

**Comment by bholagabbar** [comment]
Yup just noticed this. Working on it

**Comment by bholagabbar** [comment]
Fixed in commits https://github.com/OpenSRP/openmrs-module-cohort/commit/0c00a9e16738ec1d38cb05543bce5d4272d7c7bc , https://github.com/OpenSRP/openmrs-module-cohort/commit/66bea5774833a2d736d42c1ab7bf560d95e854ff , https://github.com/OpenSRP/openmrs-module-cohort/commit/c88b9edb03a3d91a8687d522ac0209fe10a9d27b , https://github.com/OpenSRP/openmrs-module-cohort/commit/509ca4160ee00027ef5d5b719954e97b78799bbc

Please check the edit functionality now. It should be working. I'll create a new release too
