### ISSUE TITLE
Auto-adjust UI on the page so menu bar doesn't cover page content when the user makes the browser window smaller

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-cohort#5]
![screen shot 2016-08-02 at 12 03 01 pm](https://cloud.githubusercontent.com/assets/3488986/17323123/6997dd82-58a9-11e6-822b-2bdb1a56227a.png)

In the above page screen capture (and all the pages in cohort module), there should be added space between the top heading and the top menu bar. In the above screenshot, there needs to be space between `Edit Cohort Role` and the top menu bar.

**Comment by cafootitt** [comment]
I realized this is actually related to the window size; when you make the window smaller, the menu bar at the top covers all of the content on the page. Will update the issue title to reflect this.

**Comment by cafootitt** [comment]
This is low priority.

**Comment by bholagabbar** [comment]
Never mind. I could add a Media Query that fixes it

**Comment by bholagabbar** [comment]
Fixed in commit https://github.com/OpenSRP/openmrs-module-cohort/commit/60c777d32ceff8620346d87bb50774f6c46b6e3c by adding a media query @cagulas 

![capture](https://cloud.githubusercontent.com/assets/11693595/17460711/c3900e2e-5c8f-11e6-97c5-dbb3799409aa.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11693595/17460712/c3d71d64-5c8f-11e6-95fa-ba188b97849b.PNG)
